# Generated by Django 2.2.1 on 2019-05-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
    ]
