# Generated by Django 2.2.1 on 2019-05-29 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_auto_20190519_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('courier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='controller.Courier')),
                ('length', models.IntegerField()),
                ('current', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RouteComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.TextField()),
                ('position', models.IntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.Route')),
            ],
        ),
    ]
