# Generated by Django 2.2.1 on 2019-05-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_route_routecomponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='current',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='route',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='routecomponent',
            name='json',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='routecomponent',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
