# Generated by Django 2.2.1 on 2019-05-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='session_key',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='courier',
            name='authentication_challenge',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='courier',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='courier',
            name='registration_challenge',
            field=models.CharField(default='', max_length=50),
        ),
    ]
